const LARGE_PROTOCOL_PAYLOAD_BYTES = 4 * 1024 * 1024
const JSON_STRING_ESCAPE_HEADROOM_BYTES = LARGE_PROTOCOL_PAYLOAD_BYTES
const SOCKET_ENVELOPE_HEADROOM_BYTES = 256 * 1024

export const MAX_INCOMING_MESSAGE_BYTES =
	LARGE_PROTOCOL_PAYLOAD_BYTES +
	JSON_STRING_ESCAPE_HEADROOM_BYTES +
	SOCKET_ENVELOPE_HEADROOM_BYTES

export const MAX_INCOMING_BUFFER_BYTES = MAX_INCOMING_MESSAGE_BYTES

