import type { ActionClientToServer } from './actionClientToServer.js'
import type { ActionServerToClient } from './actionServerToClient.js'
import type { ActionUtility } from './actionUtility.js'

type HandledActions = ActionClientToServer | ActionUtility
export type ActionHandlerArgs<T extends HandledActions> = Omit<T, 'action'>

export type {
	BlindKind,
	BlindRow,
	GameMode,
	LobbyNemesisAssignmentWirePayload,
	LobbyOptionsWirePayload,
	LobbyOptionWireValue,
	LobbyPlayerWirePayload,
	LobbyType,
} from './actionShared.js'

export type {
	ActionKeepAlive,
	ActionKeepAliveAck,
	ActionUtility,
} from './actionUtility.js'

export type {
	ActionConnected,
	ActionCoopBlindPreview,
	ActionCoopBossBlind,
	ActionEatPizza,
	ActionEnemyDisconnected,
	ActionEnemyInfo,
	ActionEnemyLocation,
	ActionEnemyReconnected,
	ActionEndCoopBlind,
	ActionEndPvP,
	ActionError,
	ActionGetEndGameJokersRequest,
	ActionGetEndGameSummaryRequest,
	ActionGetNemesisDeckRequest,
	ActionJoinedLobby,
	ActionJimboAppear,
	ActionJimboMove,
	ActionJimboRemove,
	ActionJimboTalk,
	ActionKickedFromLobby,
	ActionLetsGoGamblingNemesis,
	ActionLobbyInfo,
	ActionLobbyNemesisAssignments,
	ActionLobbyOptions,
	ActionLobbyPlayerJoined,
	ActionLobbyPlayerLeft,
	ActionLobbyPlayerUpdated,
	ActionLobbyPlayerTeam,
	ActionLobbyTypeChanged,
	ActionLoseGame,
	ActionMagnet,
	ActionMagnetResponse,
	ActionModded,
	ActionMoneyUpdate,
	ActionPauseAnteTimer,
	ActionPlayerInfo,
	ActionReceiveEndGameJokersRequest,
	ActionReceiveEndGameSummaryRequest,
	ActionReceiveNemesisDeckRequest,
	ActionRejoinedLobby,
	ActionRemovePhantom,
	ActionRequestVersion,
	ActionSendPhantom,
	ActionServerToClient,
	ActionSoldJoker,
	ActionSpeedrun,
	ActionSpentLastShop,
	ActionStartAnteTimer,
	ActionStartBlind,
	ActionStartGame,
	ActionAsteroid,
	ActionTeamCardSync,
	ActionTeamHandLevelSync,
	ActionTeamSkipBlind,
	ActionWinGame,
	ActionAloneGame,
	LobbyTypeChangedPlayerWirePayload,
} from './actionServerToClient.js'

export type {
	ActionClientCoopSave,
	ActionCoopSaveVote,
	ActionResumeCoopSave,
	ActionSaveCoopRun,
	ActionServerCoopSave,
	ActionStartCoopSave,
	CoopSavePlayerWirePayload,
	CoopSaveRecordWirePayload,
	CoopSaveSummaryWirePayload,
	CoopSaveSnapshotWirePayload,
} from './actionCoopSave.js'

export type {
	ActionClientToServer,
	ActionBlindPreview,
	ActionCoopBossBlindRequest,
	ActionCreateLobby,
	ActionEatPizzaRequest,
	ActionFailRound,
	ActionFailPvPTimer,
	ActionFailTimer,
	ActionGetEndGameJokersResponse,
	ActionGetEndGameSummaryResponse,
	ActionGetNemesisDeckResponse,
	ActionJoinLobby,
	ActionKickPlayer,
	ActionLeaveLobby,
	ActionLetsGoGamblingNemesisRequest,
	ActionMagnetRequest,
	ActionMagnetResponseRequest,
	ActionMakePlayerHost,
	ActionModdedRequest,
	ActionNewRound,
	ActionPauseAnteTimerRequest,
	ActionPlayHand,
	ActionReadyBlind,
	ActionReadyLobby,
	ActionReadySkipBlind,
	ActionReceiveEndGameJokersResponse,
	ActionReceiveEndGameSummaryResponse,
	ActionReceiveNemesisDeckResponse,
	ActionRejoinLobby,
	ActionReturnToLobby,
	ActionSendTeamMoney,
	ActionSetAnte,
	ActionSetFurthestBlind,
	ActionSetLobbyType,
	ActionSetLocation,
	ActionSetTeam,
	ActionSetTeamLock,
	ActionSkip,
	ActionSoldJokerRequest,
	ActionSpentLastShopRequest,
	ActionStartAnteTimerRequest,
	ActionStartGameRequest,
	ActionSyncClient,
	ActionSyncMoney,
	ActionTeamCardSyncRequest,
	ActionTeamHandLevelSyncRequest,
	ActionUnreadyBlind,
	ActionUnreadyLobby,
	ActionUnreadySkipBlind,
	ActionUsername,
	ActionVersion,
} from './actionClientToServer.js'

export type Action = ActionServerToClient | ActionClientToServer | ActionUtility
