export const MAX_TEAMS = 8

export const MIN_GROUP_LOBBY_PLAYERS = 3
export const DEFAULT_GROUP_LOBBY_PLAYERS = 16
export const MAX_GROUP_LOBBY_PLAYERS = 32

export const DEFAULT_HANDS_PER_ROUND = 4

const MILLISECONDS_PER_SECOND = 1000
const SPEEDRUN_REWARD_WINDOW_SECONDS = 30
export const SPEEDRUN_REWARD_WINDOW_MS =
	SPEEDRUN_REWARD_WINDOW_SECONDS * MILLISECONDS_PER_SECOND
